version: '3.8'
services:
  web:
    image: juanarillo/docker_practica:flask_v2
    ports:
      - "8080:5000"
    env_file:
      - ${ENV_FILE:-.env.dev}
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    hostname: ${REDIS_HOST:-redis}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - redis_data:/data
    command: ["redis-server","--loglevel", "warning", "--logfile", ""]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
volumes:
  redis_data:
  es_data: